### PR TITLE
Improve table view

### PR DESCRIPTION
**Pull request by JaronPiet**
Dear David,

thank you for that tool. I used your tool for translation and merging in our angular app. I changed and add some aspects which may bring some advantage for the user.

Notes:
1. The Tool now keeps the context information (purpose, datatype, sourcefile, linenumber's) of the origin units.
2. Source and target columns now at the very begining of the table.
3. Meta data columns visibility is optional (false by default).
4. Empty target rows will be marked (gray).
5. Duplicates only view: Shows only sources which occours multiple times.
6. Duplicates which differs in target will be marked (orange).
7. Processing to trim blanks at start and end of targets.
8. Current filepath in Window title incl. change indication
9. Add example files.
10. Change Readme

Regards,
Jaron

### CODE REVIEW

**Review by DavidOndrus — APPROVED** [review]

**Comment by DavidOndrus** [comment]
Hello, thanks for using my tool and even more for updating it. Nice to hear that it helped you. Changes you've implemented make sense and I see added value for users in them but since I don't work with the technology it's meant for, I don't use nor maintain this tool anymore. Still, I want to help spread handy functionality across community so I would like to suggest another way - I would prefer to not continue adding changes to my repository since I have limited time to review them and also I don't want to take credits for them because you've done all the work. Would you agree stating your fork repository in my README as continuation of this tool so it will navigate users to you ?

Thank you for your work

**Comment by JaronPiet** [comment]
Hi, i agree with that.

**Comment by JaronPiet** [comment]
I released version 1.6 at my repository.

**Comment by DavidOndrus** [comment]
Ok thanks for understanding and cooperation. I'm going to close these pull requests and state your project in my README.

**Pull request closed without merging**
